# Docker composer file for Linux User
version: '3.2'
services:
  yocto-dev:
    image: bacnh85/yocto-dev
    container_name: yocto-dev
    environment: 
      - UID=1000
      - GID=1000
    volumes:
      - ../:/opt
      - ~/.ssh:/home/1000/.ssh
      - ~/.gitconfig:/home/1000/.gitconfig
    tty: true   
