# Docker composer file for Linux User
version: '3.2'
services:
  sc20-dev-machine:
    image: bacnh85/yocto-tegra
    container_name: yocto-tegra
    environment: 
      - UID=1000
      - GID=1000
    volumes:
      - ./:/opt
      - ~/.ssh:/home/1000/.ssh
      - ~/.gitconfig:/home/1000/.gitconfig
    tty: true   
